### ISSUE TITLE
debugging with current structure

### ISSUE THREAD

**Issue by azerafati** [AlrikOlson/angular-4-universal-seed#2]
Do you have any specific solution about how to debug the project in with a IDE (i.e. WebStorm)? 
In the current structure of the project, all files are compiled to JS files into `dist` folder and  I can't think of any way to debug the Type Script files in the current setup. Any solution or recommendation?

**Comment by AlrikOlson** [comment]
I've only ever used Chrome and Visual Studio Code to do my debugging, as you can debug the TypeScript right inside the Developer Console.

I found [this](https://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/) article on debugging webpack applications in WebStorm. I hope it can help!
